python -u preprocess_and_compute_HMMs.py 25 &> preprocess_and_compute_HMMs_25.out &
python -u preprocess_and_compute_HMMs.py 50 &> preprocess_and_compute_HMMs_50.out &
python -u preprocess_and_compute_HMMs.py 75 &> preprocess_and_compute_HMMs_75.out &
python -u preprocess_and_compute_HMMs.py 100 &> preprocess_and_compute_HMMs_100.out &
python -u preprocess_and_compute_HMMs.py 125 &> preprocess_and_compute_HMMs_125.out &
python -u preprocess_and_compute_HMMs.py 150 &> preprocess_and_compute_HMMs_150.out &
python -u preprocess_and_compute_HMMs.py 175 &> preprocess_and_compute_HMMs_175.out &
python -u preprocess_and_compute_HMMs.py 200 &> preprocess_and_compute_HMMs_200.out &
python -u preprocess_and_compute_HMMs.py 225 &> preprocess_and_compute_HMMs_225.out &
python -u preprocess_and_compute_HMMs.py 250 &> preprocess_and_compute_HMMs_250.out &
python -u preprocess_and_compute_HMMs.py 275 &> preprocess_and_compute_HMMs_275.out &
python -u preprocess_and_compute_HMMs.py 300 &> preprocess_and_compute_HMMs_300.out &
python -u preprocess_and_compute_HMMs.py 325 &> preprocess_and_compute_HMMs_325.out &
python -u preprocess_and_compute_HMMs.py 350 &> preprocess_and_compute_HMMs_350.out &
python -u preprocess_and_compute_HMMs.py 375 &> preprocess_and_compute_HMMs_375.out &
python -u preprocess_and_compute_HMMs.py 400 &> preprocess_and_compute_HMMs_400.out &
python -u preprocess_and_compute_HMMs.py 500 &> preprocess_and_compute_HMMs_500.out &
python -u preprocess_and_compute_HMMs.py 600 &> preprocess_and_compute_HMMs_600.out &
python -u preprocess_and_compute_HMMs.py 700 &> preprocess_and_compute_HMMs_700.out &
python -u preprocess_and_compute_HMMs.py 800 &> preprocess_and_compute_HMMs_800.out &
python -u preprocess_and_compute_HMMs.py 900 &> preprocess_and_compute_HMMs_900.out &
python -u preprocess_and_compute_HMMs.py 1000 &> preprocess_and_compute_HMMs_1000.out &
